name: Generate Metrics SVG

# Controls when the action will run. 
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: GitHub metrics as SVG image
        # You may pin to the exact commit or the version.
        # uses: lowlighter/metrics@db876713ebb058ea669c16708e1a6142ae50d5e9
        uses: lowlighter/metrics@v3.1
        with:
          token: "${{ secrets.PAT }}"
          committer_token: "${{ secrets.GITHUB_TOKEN }}" 
          user: RemeJuan
          config_timezone: "Africa/Johannesburg"
          template: repository
          plugin_pagespeed: true
          plugin_lines: true
          plugin_traffic: true
          plugin_habits: true
          plugin_habits_charts: true
          plugin_languages: true
          plugin_languages_ignored: "html"
          plugin_followup: true
          plugin_music: true
          plugin_music_provider: "apple"
          plugin_music_mode: "recent"
          plugin_posts: true
          plugin_posts_source: "dev.to"
          plugin_posts_user: "@remejuan" 
          plugin_isocalendar: true
          plugin_gists: true
          plugin_topics: true
          plugin_projects: true
          plugin_tweets: true
          plugin_tweets_user: "RemeJuan" 
          plugin_tweets_token: "${{ secrets.TWIT_BEARER }}"  
          plugin_tweets_limit: 4
          plugin_stars: true
          plugin_stargazers: true
